### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [jomo/SimpleTorch#1]
Publish it there, or if already done, best add a download link to the Readme.

**Comment by jomo** [comment]
I usually would, but this is a 6 year old project for Android 2.3. I'm not sure if it would even run on current Android versions.

There are a handful of alternatives on F-Droid that do the same (just search for `torch`), e.g. [SecUSo/privacy-friendly-torchlight](https://github.com/SecUSo/privacy-friendly-torchlight).

I'll add this note to the README.

**Comment by rugk** [comment]
Yep, you can also [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
